project:
  type: website

website:
  navbar: 
    title: "Gráficos"
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jorgemartmarc
  page-footer:
    right: "Jorge Martín Marcos"
  favicon: 0_img/icono_g.png
  bread-crumbs: false # Para que elimie de la parte superior las indicaciones de dónde se está (P.ej., que no aparezca: Análisis de datos > Análisis bivariado > Ttest )
  page-navigation: true # Para que al final de cada página aparezca una opción de ir a la siguiente página o a la anterior.
  back-to-top-navigation: true # Para que al final de cada página aparezca una opción para subir otra vez al principio.
  search: true # Para añadir la lupa a la página
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Ejemplos
      - g_mancuernas.qmd
      - g_lineas.qmd
      - g_barras.qmd
      - g_otros.qmd
format:
  html:
    theme: # Se puede añadir una opción para poner la página en modo claro o modo oscuro
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-title: "Contenido"    
    language: es              
    include-in-header:
      - text: |
          <style>
          /* Estilos para todo el documento */
          body {
            text-align: justify;
          }
          /* Estilos específicos para la tabla de contenidos */
          .toc-actions, .toc .nav, .toc .nav > li > a {
            text-align: left !important;
          }
          </style>
      - text: |
          <script>
          // Añadir funcionalidad de zoom para imágenes
          document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('img.zoomable').forEach(function(img) {
              img.addEventListener('click', function() {
                this.classList.toggle('zoomed');
              });
            });
          });
          </script>


editor: visual

