project:
  type: website

website:
  title: "Gráficos"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - g_puntos.qmd
      - g_lineas.qmd
      - g_barras.qmd
      - g_otros.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

